name: Build plugin with Maven
on: [push, pull_request]
jobs:
  maven:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
          check-latest: true
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: target/*.jar
